<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>10&nbsp; Recovery Results: Does Pipeline C Find the Truth? – Making Pipelines B and C Legible</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./11-pipeline-b-tempering.html" rel="next">
<link href="./09-controlled-experiment.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-544537484d1132e2332c9966fc148d9a.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-controlled-experiment.html">IV · Simulated-Data Demonstration</a></li><li class="breadcrumb-item"><a href="./10-recovery-results.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Recovery Results: Does Pipeline C Find the Truth?</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Making Pipelines B and C Legible</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/joonho112/one-mcmc-pv-memo" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">I · Orientation</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-three-pipelines-one-picture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">The Three Pipelines in One Picture</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-questions-and-roadmap.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Your Questions, Restated — and a Roadmap</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">II · Mathematical Theory</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-licensing-identity.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The Licensing Identity: One Fit Gives the Pooled Point Estimate</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-pv-to-parameter-variance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">From Plausible-Value Variance to Parameter Variance</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-where-tmi-comes-from.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Where the External Variance Comes From: BRR-Fay Assembly</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06-ccc-beta-only.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">The Cholesky Calibration Correction, and Why Only the Betas</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07-pipeline-b-importance-sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Pipeline B: Importance Sampling, Tempering, and Diagnostics</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">III · Code</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08-operators-in-code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">The Operators in Code</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">IV · Simulated-Data Demonstration</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09-controlled-experiment.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">A Controlled Experiment with Known Truth</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10-recovery-results.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Recovery Results: Does Pipeline C Find the Truth?</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11-pipeline-b-tempering.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Pipeline B in Practice: a Tempering Experiment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true">
 <span class="menu-text">V · PISA 2022 Application</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12-pisa-data-model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">PISA 2022: Data and Model Setup</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13-pisa-results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">PISA 2022: Three Pipelines, Side by Side</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true">
 <span class="menu-text">VI · Synthesis</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14-response-to-matt.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Response to Your Comments</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-recovery" id="toc-sec-recovery" class="nav-link active" data-scroll-target="#sec-recovery"><span class="header-section-number">10.1</span> What came out</a></li>
  <li><a href="#theorem-2.2-holds-to-machine-precision" id="toc-theorem-2.2-holds-to-machine-precision" class="nav-link" data-scroll-target="#theorem-2.2-holds-to-machine-precision"><span class="header-section-number">10.2</span> 1. Theorem 2.2 holds to machine precision</a></li>
  <li><a href="#the-variance-component-boundary-is-real-and-shrinks-with-scale" id="toc-the-variance-component-boundary-is-real-and-shrinks-with-scale" class="nav-link" data-scroll-target="#the-variance-component-boundary-is-real-and-shrinks-with-scale"><span class="header-section-number">10.3</span> 2. The variance-component boundary is real — and shrinks with scale</a></li>
  <li><a href="#the-deployed-sampler-sits-right-next-to-the-identity" id="toc-the-deployed-sampler-sits-right-next-to-the-identity" class="nav-link" data-scroll-target="#the-deployed-sampler-sits-right-next-to-the-identity"><span class="header-section-number">10.4</span> 3. The deployed sampler sits right next to the identity</a></li>
  <li><a href="#pipeline-c-direct-equals-pipeline-a-exactly-in-point-and-se" id="toc-pipeline-c-direct-equals-pipeline-a-exactly-in-point-and-se" class="nav-link" data-scroll-target="#pipeline-c-direct-equals-pipeline-a-exactly-in-point-and-se"><span class="header-section-number">10.5</span> 4. Pipeline C-Direct equals Pipeline A — exactly, in point and SE</a></li>
  <li><a href="#pipeline-b-the-gate-passes-in-the-pilot-and-fires-at-scale" id="toc-pipeline-b-the-gate-passes-in-the-pilot-and-fires-at-scale" class="nav-link" data-scroll-target="#pipeline-b-the-gate-passes-in-the-pilot-and-fires-at-scale"><span class="header-section-number">10.6</span> 5. Pipeline B: the gate passes in the pilot, and fires at scale</a></li>
  <li><a href="#coverage-is-nominal" id="toc-coverage-is-nominal" class="nav-link" data-scroll-target="#coverage-is-nominal"><span class="header-section-number">10.7</span> 6. Coverage is nominal</a></li>
  <li><a href="#sec-design-coverage" id="toc-sec-design-coverage" class="nav-link" data-scroll-target="#sec-design-coverage"><span class="header-section-number">10.8</span> 7. Design-based coverage under informative sampling</a></li>
  <li><a href="#reading-the-result" id="toc-reading-the-result" class="nav-link" data-scroll-target="#reading-the-result"><span class="header-section-number">10.9</span> Reading the result</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/joonho112/one-mcmc-pv-memo/blob/main/10-recovery-results.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/joonho112/one-mcmc-pv-memo/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./09-controlled-experiment.html">IV · Simulated-Data Demonstration</a></li><li class="breadcrumb-item"><a href="./10-recovery-results.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Recovery Results: Does Pipeline C Find the Truth?</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Recovery Results: Does Pipeline C Find the Truth?</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sec-recovery" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="sec-recovery"><span class="header-section-number">10.1</span> What came out</h2>
<p>All four checks of <a href="09-controlled-experiment.html#sec-controlled" class="quarto-xref"><span>Section 9.1</span></a> ran on the known-truth data — at both the <span class="math inline">\(J=60\)</span> pilot and the <span class="math inline">\(J=150\)</span> PISA-scale design, through the <strong>real</strong> pipeline functions. The headline: <strong>one stacked MCMC, calibrated to an externally assembled target centered at <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span>, reproduces the ten-fit Rubin report exactly — point estimate <em>and</em> standard error — recovers the true coefficients at PISA scale, and, on the same run, reproduces Pipeline B’s importance-sampling breakdown when the design grows.</strong> Here is each check.</p>
</section>
<section id="theorem-2.2-holds-to-machine-precision" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="theorem-2.2-holds-to-machine-precision"><span class="header-section-number">10.2</span> 1. Theorem 2.2 holds to machine precision</h2>
<p>The per-PV GLS estimates, averaged, and the stacked GLS solution on <span class="math inline">\(\bar y\)</span> agree to floating point at both scales: <span class="math display">\[
\bigl\|\hat\beta^q - \bar\beta_{\text{Rubin}}\bigr\|_\infty
  = 6.4\times 10^{-15}\ (J=150), \qquad 1.0\times 10^{-14}\ (J=60).
\]</span> At PISA scale both equal <span class="math inline">\(\bar\beta_{\text{Rubin}} = (0.042,\ 0.385,\ 0.525)\)</span> for (intercept, <span class="math inline">\(\beta^W\)</span>, <span class="math inline">\(\beta^B\)</span>). This is not an approximation that improves with sample size — it is the exact algebraic identity of <a href="03-licensing-identity.html#sec-identity" class="quarto-xref"><span>Section 3.1</span></a>, visible in the output. One fit gives the pooled point estimate. (This triple is the closed-form GLS <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span> at a common plug-in precision — the object Theorem 2.2 is about. Pipeline A’s <em>per-PV-refit</em> estimate reported in §4, <span class="math inline">\((0.042,\,0.386,\,0.527)\)</span>, is the same target computed by ten separate refits rather than one plug-in solve, and so differs only in the third decimal; the two are not meant to be bit-identical, only to recover the same <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span>.)</p>
</section>
<section id="the-variance-component-boundary-is-real-and-shrinks-with-scale" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="the-variance-component-boundary-is-real-and-shrinks-with-scale"><span class="header-section-number">10.3</span> 2. The variance-component boundary is real — and shrinks with scale</h2>
<p>As predicted, the identity does <strong>not</strong> extend to the variance components — and now we can watch the gap close as the design grows. The per-PV REML estimate of <span class="math inline">\(\sigma^2_{\text{school}}\)</span>, averaged over the ten PVs, against the stacked-fit estimate:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>scale</th>
<th style="text-align: center;">per-PV REML avg</th>
<th style="text-align: center;">stacked-fit</th>
<th style="text-align: center;">drift</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(J=60\)</span> (pilot)</td>
<td style="text-align: center;">0.395</td>
<td style="text-align: center;">0.414</td>
<td style="text-align: center;"><span class="math inline">\(+4.7\%\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(J=150\)</span> (PISA-scale)</td>
<td style="text-align: center;">0.297</td>
<td style="text-align: center;">0.299</td>
<td style="text-align: center;"><span class="math inline">\(+0.7\%\)</span></td>
</tr>
</tbody>
</table>
<p>This is exactly the honest falsification <a href="03-licensing-identity.html#sec-identity" class="quarto-xref"><span>Section 3.1</span></a> promised: the fixed-effect identity is exact (<span class="math inline">\(10^{-14}\)</span>) while the variance-component “identity” is not. But the drift is a <em>small-sample</em> artifact, not a structural one — it falls from <span class="math inline">\(4.7\%\)</span> at <span class="math inline">\(J=60\)</span> to under one percent at PISA’s school count, computed here on our own data rather than asserted. Either way, this is the formal reason the calibration of <a href="06-ccc-beta-only.html#sec-ccc" class="quarto-xref"><span>Section 6.1</span></a> touches only <span class="math inline">\(\beta_{\text{FE}}\)</span>.</p>
</section>
<section id="the-deployed-sampler-sits-right-next-to-the-identity" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="the-deployed-sampler-sits-right-next-to-the-identity"><span class="header-section-number">10.4</span> 3. The deployed sampler sits right next to the identity</h2>
<p>The real <code>brms</code> stacked fractional fit — one MCMC — returned a raw posterior mean a short distance from the exact Rubin estimate: <span class="math display">\[
\bigl\|\,\text{raw posterior mean} - \bar\beta_{\text{Rubin}}\,\bigr\|_\infty
  = 0.013\ (J=150), \qquad 0.091\ (J=60).
\]</span> This is the R3a→R3b gap of <a href="03-licensing-identity.html#sec-identity" class="quarto-xref"><span>Section 3.1</span></a>, <em>measured</em> rather than assumed — and, like the variance-component drift, it shrinks toward the plug-in identity as the design grows: at PISA scale the deployed sampler lands about one hundredth of a unit from it. <strong>Crucially, this gap no longer touches the Pipeline C-Direct point estimate.</strong> With the external-center construction of <a href="06-ccc-beta-only.html#sec-ccc" class="quarto-xref"><span>Section 6.1</span></a>, C-Direct is centered at <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span> <em>by construction</em>, so its reported point estimate equals Pipeline A’s exactly (§4). The raw-posterior-mean gap is now a <em>verification diagnostic</em> — a check that the deployed sampler sits close to the identity — not a discrepancy carried into the deliverable.</p>
</section>
<section id="pipeline-c-direct-equals-pipeline-a-exactly-in-point-and-se" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="pipeline-c-direct-equals-pipeline-a-exactly-in-point-and-se"><span class="header-section-number">10.5</span> 4. Pipeline C-Direct equals Pipeline A — exactly, in point and SE</h2>
<p>This is the central result, and it is now exact in <strong>both</strong> coordinates. Running both pipelines through the real <code>pipeline_c_direct</code> (external center <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span>) and Rubin pooling at PISA scale:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th></th>
<th style="text-align: center;">truth</th>
<th style="text-align: center;">Pipeline A est (SE)</th>
<th style="text-align: center;">Pipeline C-Direct est (SE)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\beta^W\)</span> (within)</td>
<td style="text-align: center;">0.40</td>
<td style="text-align: center;">0.386 (0.020)</td>
<td style="text-align: center;">0.386 (0.020)</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta^B\)</span> (between)</td>
<td style="text-align: center;">0.60</td>
<td style="text-align: center;">0.527 (0.071)</td>
<td style="text-align: center;">0.527 (0.071)</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\max\bigl|\hat\beta_C - \hat\beta_A\bigr| = 0\ \text{(point, exact)}, \qquad
\max\bigl|\text{SE}_C - \text{SE}_A\bigr| = 2.1\times10^{-17}.
\]</span></p>
<p>Three things to read off. First, <strong>the point estimates are now identical</strong> — the external-center calibration centers C-Direct on the very <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span> that Pipeline A reports, closing the small R3b point gap an earlier draft carried. Second, <strong>the standard errors are identical</strong>, because the Cholesky Calibration Correction reshapes the single posterior’s covariance to exactly the same <span class="math inline">\(T_{\text{MI}}\)</span> that Pipeline A assembles by Rubin pooling; the residual <span class="math inline">\(2\times10^{-17}\)</span> is floating-point noise, and — we verified independently — C’s SE is re-derived as <span class="math inline">\(\sqrt{\operatorname{diag} T_{\text{MI}}}\)</span>, the same matrix, not a copied object. This equality is exact <em>by construction</em>, not an independent corroboration: the CCC targets the very <span class="math inline">\(T_{\text{MI}}\)</span> that A’s Rubin pooling produces, so the genuinely independent evidence is that the <em>points</em> coincide and that both recover truth. Third, both pipelines do recover the truth at PISA scale: <span class="math inline">\(\beta^W=0.386\)</span> covers <span class="math inline">\(0.40\)</span> and <span class="math inline">\(\beta^B=0.527\)</span> covers <span class="math inline">\(0.60\)</span>, each within its interval (<a href="#fig-recovery" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>, left).</p>
<p><strong>An honest word on the pilot.</strong> At <span class="math inline">\(J=60\)</span> the same exact <span class="math inline">\(C=A\)</span> identity holds (point <span class="math inline">\(0\)</span>, SE <span class="math inline">\(3\times10^{-17}\)</span>), but the single-draw between-slope estimate is high — <span class="math inline">\(\beta^B = 0.776\)</span> with a <em>real</em> BRR-Fay SE of <span class="math inline">\(0.074\)</span>, so its interval <span class="math inline">\([0.63,\,0.92]\)</span> misses <span class="math inline">\(0.60\)</span>. This is not pipeline bias: with only 60 schools the contextual mean <span class="math inline">\(\bar x_{\cdot j}\)</span> is a noisy proxy for the latent school level, and the between-slope estimator drifts upward — a textbook few-cluster effect that the move to <span class="math inline">\(J=150\)</span> resolves. This is why <a href="09-controlled-experiment.html#sec-controlled" class="quarto-xref"><span>Section 9.1</span></a> assigns recovery-reading to the PISA-scale run <em>in advance</em>, where BRR-Fay has the PSUs it needs; the pilot’s pre-assigned role is to exercise Pipeline B, not to certify recovery. (Per- coefficient coverage on a <em>single</em> dataset is anyway binary; the rate is settled by the replication study in §6.)</p>
</section>
<section id="pipeline-b-the-gate-passes-in-the-pilot-and-fires-at-scale" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="pipeline-b-the-gate-passes-in-the-pilot-and-fires-at-scale"><span class="header-section-number">10.6</span> 5. Pipeline B: the gate passes in the pilot, and fires at scale</h2>
<p>The fourth pipeline tells a story the first three cannot. <code>pipeline_b_stacked_psis</code> accepts or refuses on a Pareto-<span class="math inline">\(\hat k\)</span> diagnostic (<a href="07-pipeline-b-importance-sampling.html#sec-pipeb" class="quarto-xref"><span>Section 7.1</span></a>); we ran it at both scales:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 31%">
<col style="width: 31%">
<col style="width: 18%">
</colgroup>
<thead>
<tr class="header">
<th>scale</th>
<th style="text-align: center;">max Pareto <span class="math inline">\(\hat k\)</span></th>
<th style="text-align: center;">gate (0.7)</th>
<th>outcome</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(J=60\)</span> (pilot)</td>
<td style="text-align: center;">0.37</td>
<td style="text-align: center;"><strong>passes</strong></td>
<td>B emits via <code>engine_ccc</code>; <span class="math inline">\(\hat\beta^W_B = 0.426\)</span>, beside A’s <span class="math inline">\(0.429\)</span></td>
</tr>
<tr class="even">
<td><span class="math inline">\(J=150\)</span> (PISA-scale)</td>
<td style="text-align: center;">0.83</td>
<td style="text-align: center;"><strong>fires</strong></td>
<td>islands: B refuses, falls back to C-Direct (NA emitted)</td>
</tr>
</tbody>
</table>
<p>At the pilot scale this is the positive control the review asked for: Pipeline B genuinely invokes the <em>weighted</em> calibration engine — <code>engine_ccc</code> runs per PV along its PSIS-weighted path (the importance weights enter as <code>draw_weights</code>), reshaping the calibrated cloud to its BRR-Fay target. Its accepted within-slope, <span class="math inline">\(0.426\)</span>, sits a few thousandths from Pipeline A’s <span class="math inline">\(0.429\)</span> — exactly the <span class="math inline">\(O_p(S^{-1/2})\)</span> non-exactness expected of the importance-sampling route (<a href="07-pipeline-b-importance-sampling.html#sec-pipeb" class="quarto-xref"><span>Section 7.1</span></a>), which confirms B is the genuine approximate path, not silently copying A. It is not a moment-matching shortcut; the engine actually runs (<a href="#fig-recovery" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>, right).</p>
<p>At the simulated PISA scale (<span class="math inline">\(J=150\)</span>), the <em>same</em> code on a larger design sees its stacked importance ratios collapse onto a few draws: the maximum Pareto <span class="math inline">\(\hat k\)</span> climbs to <span class="math inline">\(0.83\)</span>, past the <span class="math inline">\(0.7\)</span> gate, and Pipeline B does the safe thing — it refuses to emit and falls back to C-Direct. This is the “islands” failure that motivates C-Direct as the default (taken up in <a href="11-pipeline-b-tempering.html#sec-tempering" class="quarto-xref"><span>Section 11.1</span></a> and <a href="14-response-to-matt.html#sec-response" class="quarto-xref"><span>Section 14.1</span></a>), reproduced here by our own code rather than asserted. That breach is specific to this simulation’s structure at <span class="math inline">\(J=150\)</span>, not an automatic consequence of sample size: on the <em>real</em> PISA reading data at comparable <span class="math inline">\(J\)</span> the same gate passes comfortably (<span class="math inline">\(\hat k\le0.07\)</span>, <a href="13-pisa-results.html#sec-pisa-results" class="quarto-xref"><span>Section 13.1</span></a>). The experiment shows the gate <em>can</em> fire and that B fails safe when it does — not that it must fire whenever <span class="math inline">\(n\)</span> is large. Note the direction of dependence: C-Direct is not a fallback patched in to cover a broken B — it is the <em>default</em> (<a href="07-pipeline-b-importance-sampling.html#sec-pipeb" class="quarto-xref"><span>Section 7.1</span></a>), and B is the diagnostic run alongside it. The gate firing reports something true about the data (the per-PV modes have separated into islands); it does not put the deliverable in trouble, because the C-Direct deliverable never built importance weights in the first place. That a single experiment exhibits both the accept and the refuse path, on the same estimand, is the strongest evidence we can offer that the gate is doing real work.</p>
<div id="fig-recovery" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-recovery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/sim_realpipe.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-recovery-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.1: Left: Pipeline A vs Pipeline C-Direct point estimates and 95% intervals at PISA scale (<span class="math inline">\(J=150\)</span>) against the dashed truth — the two pipelines are indistinguishable (<span class="math inline">\(\max|C-A|=0\)</span> in point, <span class="math inline">\(2\times10^{-17}\)</span> in SE) and both slopes cover. Right: Pipeline B’s maximum Pareto <span class="math inline">\(\hat k\)</span> at the two scales against the <span class="math inline">\(0.7\)</span> gate — the bridge accepts in the pilot (and runs the calibration engine) and fires at PISA scale (islands → fallback).
</figcaption>
</figure>
</div>
</section>
<section id="coverage-is-nominal" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="coverage-is-nominal"><span class="header-section-number">10.7</span> 6. Coverage is nominal</h2>
<p>Repeating the <strong>closed-form (R3a) pipeline</strong> over 200 fresh pilot datasets — fast enough to replicate at this scale — the empirical coverage of the nominal 95% intervals was:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>coefficient</th>
<th style="text-align: center;">coverage (nominal 0.95)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>intercept</td>
<td style="text-align: center;">0.965</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\beta^W\)</span> (within)</td>
<td style="text-align: center;">0.945</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\beta^B\)</span> (between)</td>
<td style="text-align: center;">0.955</td>
</tr>
</tbody>
</table>
<p>All three land on <span class="math inline">\(0.95\)</span>. The <span class="math inline">\((\bar\beta_{\text{Rubin}}, T_{\text{MI}})\)</span> report that Pipeline C-Direct produces from one MCMC is correctly calibrated — including for the noisy between-school coefficient, whose wide intervals are <em>right</em>, not loose. (This settles the single-draw pilot miss of §4: across 200 replications of the <em>same</em> generating model, the <em>same</em> between-school coefficient’s interval covers at <span class="math inline">\(0.955\)</span> — so <span class="math inline">\(\beta^B=0.776\)</span> on one dataset is one tail draw from a correctly-centered sampling distribution, not bias.)</p>
<p>Two honest qualifications belong here. First, this is <strong>model-based</strong> coverage of the <strong>closed-form (R3a)</strong> object under equal-probability sampling; the deployed Pipeline C samples the variance components (R3b) and inherits the calibration only insofar as the R3a→R3b gap is small — measured above at <span class="math inline">\(0.013\)</span> at PISA scale, a fraction of the standard error. A <em>design-based</em> coverage study under informative sampling, the case that matters for PISA’s two-stage weights, is the subject of <a href="#sec-design-coverage" class="quarto-xref"><span>Section 10.8</span></a>, next. Second, the equality <span class="math inline">\(\text{SE}_C = \text{SE}_A\)</span> is exact <em>by construction</em> — the CCC targets the very same <span class="math inline">\(T_{\text{MI}}\)</span> — so the genuinely independent evidence in this chapter is the point-estimate identity, the recovery at scale, the Pipeline B gate behavior, and this coverage, not the SE match, which is algebra.</p>
</section>
<section id="sec-design-coverage" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="sec-design-coverage"><span class="header-section-number">10.8</span> 7. Design-based coverage under informative sampling</h2>
<p>The coverage study of §6 is <em>model-based</em> and assumes equal-probability sampling. Comments C2 and C4 press the harder case: does the BRR-Fay design variance — the <span class="math inline">\(T_{\text{MI}}\)</span> machinery every pipeline shares — deliver nominal coverage when the sample is drawn with <em>unequal, outcome-correlated</em> probabilities, the regime PISA’s two-stage weights are built for? A second known-truth experiment puts it under exactly that stress (<code>code/10_design_coverage.R</code>).</p>
<p>We fix a finite population of <span class="math inline">\(4{,}000\)</span> schools in a two-level world (<span class="math inline">\(\beta^W=0.40\)</span>, <span class="math inline">\(\beta^B=0.60\)</span>, ICC <span class="math inline">\(0.25\)</span>) and draw <span class="math inline">\(1{,}000\)</span> samples from it: schools enter through a stratified, two-per-stratum <em>equal-probability</em> design — an unstressed control — while within each sampled school students are selected with probability rising in their own outcome, the <em>endogenous</em>, outcome-dependent selection that carries the informativeness here (about <span class="math inline">\(80\)</span> schools, <span class="math inline">\(1{,}900\)</span> students per draw). The within-school SES gradient <span class="math inline">\(\beta^W\)</span> is therefore the informatively-stressed estimand; the between-school gradient <span class="math inline">\(\beta^B\)</span> rides along as a control. On each sample we estimate the within/between slopes three ways and check 95% interval coverage of the finite-population coefficients:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>estimator</th>
<th style="text-align: center;"><span class="math inline">\(\beta^W\)</span> coverage</th>
<th style="text-align: center;"><span class="math inline">\(\beta^B\)</span> coverage</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>design-weighted + BRR-Fay</strong></td>
<td style="text-align: center;"><strong>0.92</strong></td>
<td style="text-align: center;"><strong>0.94</strong></td>
</tr>
<tr class="even">
<td>unweighted + model-based SE</td>
<td style="text-align: center;">0.76</td>
<td style="text-align: center;">0.54</td>
</tr>
<tr class="odd">
<td>weighted point + model-based SE</td>
<td style="text-align: center;">0.07</td>
<td style="text-align: center;">0.04</td>
</tr>
</tbody>
</table>
<p>Three things to read off (<a href="#fig-design-coverage" class="quarto-xref">Figure&nbsp;<span>10.2</span></a>). First, <strong>the design weights remove the bias</strong>: ignoring them pulls the within-slope estimate off the truth by about <span class="math inline">\(0.035\)</span> (panel b, red), while the weighted estimator is centered on it (green). Second, <strong>the BRR-Fay sandwich restores nominal coverage</strong> — <span class="math inline">\(0.92\)</span>–<span class="math inline">\(0.94\)</span> against the <span class="math inline">\(0.95\)</span> target. Third, and most pointedly, <strong>the variance object is doing the work, not just the weights</strong>: the third row uses the <em>correct</em> weighted point estimate but a <em>model-based</em> standard error that ignores the clustered, weighted design, and it covers at <span class="math inline">\(0.07\)</span> and <span class="math inline">\(0.04\)</span> — a catastrophic failure. Getting the point estimate right is not enough; the design variance is what makes the interval honest.</p>
<p>One honest note: the within-slope coverage (<span class="math inline">\(0.92\)</span>) sits a hair below nominal because a school-level (PSU) replicate method slightly under-propagates the <em>within</em>-school student-sampling variance — a known, mild conservatism of replicate weights for within-cluster slopes, and a rounding error beside the naive analyses’ collapse. The between-school slope, the estimand the parent paper headlines, lands at <span class="math inline">\(0.94\)</span>.</p>
<p>This is the design-based complement to §6: the same BRR-Fay <span class="math inline">\(T_{\text{MI}}\)</span> that Pipeline C-Direct calibrates to is not merely model-correct under equal-probability sampling — it stays calibrated under <em>informative</em>, unequal-probability selection. One honest boundary on the claim: the informativeness here is <em>within-school</em> (student-level); the school stage is equal-probability, so this establishes design-validity under within-PSU informative selection, not yet under informative <em>PSU</em> (school) selection — the harder, two-stage-weight case that is the parent paper’s own headline, and which we flag as the natural next stress-test rather than assert.</p>
<div id="fig-design-coverage" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-design-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/design_coverage.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-design-coverage-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10.2: (a) 95% interval coverage under informative sampling for the within- and between-school slopes: the design-weighted BRR-Fay estimator (green) sits at the <span class="math inline">\(0.95\)</span> line, while ignoring the weights (red) or using a model-based SE on the <em>correct</em> weighted point (orange) under-covers badly. (b) The within-slope sampling distribution — design-weighting (green) is centered on the truth; the unweighted estimator (red) is shifted off by the informative selection.
</figcaption>
</figure>
</div>
</section>
<section id="reading-the-result" class="level2" data-number="10.9">
<h2 data-number="10.9" class="anchored" data-anchor-id="reading-the-result"><span class="header-section-number">10.9</span> Reading the result</h2>
<p>On data where we know the answer, Pipeline C-Direct — a single stacked MCMC plus one deterministic CCC pass against an externally assembled <span class="math inline">\(T_{\text{MI}}\)</span> centered at <span class="math inline">\(\bar\beta_{\text{Rubin}}\)</span> — reproduced Pipeline A’s point estimate <em>and</em> its exact standard errors, recovered the true coefficients at PISA scale, and achieved nominal coverage; and the same run exhibited Pipeline B accepting in the pilot and failing safe at scale. The variance components, honestly, do not inherit the exact identity, but their drift shrinks to under a percent at PISA’s school count, which is why they are left uncalibrated and deferred. Everything Part II claimed on paper is visible here in output, computed with the real pipeline code. The remaining question — does it hold on the actual PISA data, with real two-stage weights — is Part V.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/joonho112\.github\.io\/one-mcmc-pv-memo\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./09-controlled-experiment.html" class="pagination-link" aria-label="A Controlled Experiment with Known Truth">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">A Controlled Experiment with Known Truth</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./11-pipeline-b-tempering.html" class="pagination-link" aria-label="Pipeline B in Practice: a Tempering Experiment">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Pipeline B in Practice: a Tempering Experiment</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




<footer class="footer"><div class="nav-footer"><div class="nav-footer-center"><div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/joonho112/one-mcmc-pv-memo/blob/main/10-recovery-results.qmd" class="toc-action"><i class="bi bi-github"></i>View source</a></li><li><a href="https://github.com/joonho112/one-mcmc-pv-memo/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li></ul></div></div></div></footer></body></html>